#pragma config(Sensor, S1,     xHome,          sensorEV3_Touch)
#pragma config(Sensor, S3,     yHome,          sensorEV3_Touch)
#pragma config(Sensor, S4,     xHome2,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          xMotor,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          yMotor,        tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          xMotor2,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          pumpMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "EV3Mailbox.c"
#include "xy-plot.c"

task main()
{
	displayBigTextLine(0, "Started!");

	char action[MAX_MSG_LENGTH];
	char *payload;

	openMailboxIn("EV3_INBOX0");

	while (true)
	{
		readMailboxIn("EV3_INBOX0", action);
		readMailboxIn("EV3_INBOX1", payload);

		if (strcmp(action, "") != 0)
		{
			playSoundFile("Download");
			writeDebugStreamLine(action);
			eraseDisplay();
			startTask(monitorPlotter);
			wait1Msec(2000);
			calibrate();

			/*******************************************
			* read input to determine action
			* strings in freeDraw are split in xy-plot
			********************************************/

			if (strcmp(action, "Circle") == 0) {
				moveEllipse(60, 100, 50, 50, 360, 20);
				} else if (strcmp(action, "Heart") == 0) {
				drawHeart(100);
				} else if (strcmp(action, "Square") == 0) {
				drawSquare(30);
				} else if (strcmp(action, "Triangle") == 0) {
				drawTriangle(30, 40);
				} else if (strcmp(action, "Star") == 0) {
				drawStar(50, 40, 20);
				}else if (strcmp(action, "Spiral") == 0) {
				drawSpiral(50, 50, 50, 20);
				}else if (strcmp(action, "Eifel") == 0) {
				drawEiffel(50, 20);
				}else if (strcmp(action, "Smiley") == 0) {
				drawSmiley(50,50,50,20);
			}else if (strcmp(action, "Text") == 0) {
				writeText(payload, 20);
				}else if (strcmp(action, "Draw") == 0) {
				freeDraw(payload, 20);
			}
			wait1Msec(1000);
			playSoundFile("Thank you");
			calibrate();
		}
		else
		{
			displayBigTextLine(8, "empty message!");
		}
	}
	closeMailboxIn("EV3_INBOX0");
	return;
}
