#pragma config(Motor,  motorA,          Sluis,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true){

		if(getButtonPress(buttonUp)){
			setMotorTarget(Sluis, -500, 100);
			waitUntilMotorStop(Sluis);
			}else if(getButtonPress(buttonDown)){
			setMotorTarget(Sluis, 500, 100);
			waitUntilMotorStop(Sluis);
			}else{
			setMotor(Sluis, 0);
		}
	}

}
