#pragma config(Sensor, S1,     Distancer,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Sluis,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int setDistance = SensorValue[Distancer];
	int secondcheck;
	setMotorTarget(Sluis, 50, 100);
	waitUntilMotorStop(Sluis);
	while(true){
		if(setDistance != SensorValue[Distancer]){
			writeDebugStreamLine("%d,%d,%d", setDistance,secondcheck,getMotorEncoder(Sluis));
			setMotorTarget(Sluis, -50, 100);
			waitUntilMotorStop(Sluis);
			setDistance = SensorValue[Distancer];
			}else{
			secondcheck = SensorValue[Distancer];
		}
		if(secondcheck == setDistance){
			setMotor(Sluis, 0);
		}
	}

}
