#pragma config(Sensor, S1,     distanceSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          pinchMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          pumpke,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void setMotorEncoder(tMotor targetMotor, int encoderTarget, int speed){
		resetMotorEncoder(targetMotor);
		while(getMotorEncoder(targetMotor) < encoderTarget) {
			setMotor(targetMotor, speed);
		}
		stopMotor(targetMotor);
		resetMotorEncoder(targetMotor);
		waitUntilMotorStop(targetMotor);
}

float distance = getUSDistance(distanceSensor);
bool pinched = true;
bool buildPressure = true;
bool distanceChanging = false;

task main()
{

	resetTimer(T1);
	setMotorEncoder(pinchMotor, 30, 50);
	writeDebugStreamLine("%d", getMotorEncoder(pinchMotor));

	while(true){
		if(getButtonPress(buttonUp)){
			setMotor(pumpke, 100);
		}

		if(distance != getUSDistance(distanceSensor)){
			distanceChanging = true;
		} else {
			distanceChanging = false;
			//writeDebugStreamLine("%d", getTimerValue(T1));
			if(getTimer(T1, milliseconds) > 12345) {
				buildPressure = true;
				resetTimer(T1);
			}
		}

		if(!buildPressure && distanceChanging && pinched) {
			setMotorEncoder(pinchMotor, -30,100);
			writeDebugStreamLine("unpinched");
			buildPressure = false;
			resetTimer(T1);
			pinched = false;
		} else if ((!pinched && !distanceChanging && !buildPressure) || (!buildPressure && !distanceChanging)) {
			writeDebugStreamLine("pinched");
			setMotorEncoder(pinchMotor, 30, 100);
			pinched = true;
			buildPressure = false;
		}

		distance = getUSDistance(distanceSensor);
		delay(100);
		/*if (initialdrukken == true){
		time1[T1];
		if(setDistance != SensorValue[Distancer] && !indrukken){
		indrukken = false;
		initialdrukken = true;
		setMotorTarget(Sluis, -50, 100);
		waitUntilMotorStop(Sluis);
		setDistance = SensorValue[Distancer];
		}else{
		indrukken = true;
		initialdrukken = false;
		secondcheck = SensorValue[Distancer];
		}
		if(secondcheck == setDistance){
		setMotor(Sluis, 0);
		}
		}else{

		}*/
	}


}
