#pragma config(Sensor, S1,     pressHome,      sensorTouch)
#pragma config(Sensor, S2,     xHome,          sensorTouch)
#pragma config(Sensor, S3,     yHome,          sensorTouch)
#pragma config(Motor,  motorA, xMotor,         tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB, yMotor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC, pressMotor,     tmotorNormal, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/********************************************************
*   Set Global Constants and Variables
********************************************************/
task monitorPlotter();
void calibrateX();
void calibrateY();
void pressBottle(bool enabled);
void moveLinear(int amountToMoveX, int amountToMoveY);


bool penPosition = false;
int xPosition, xDegrees;
int yPosition, yDegrees;


/*******************************************************
*   Monitor Plotters Variables	&amp; Display on LCD
********************************************************/
task monitorPlotter()
{
	while (true)
	{
		wait1Msec(100);
		displayBigTextLine(3, "X pos: &lt; %d&gt;", nMotorEncoder[xMotor]);
		displayBigTextLine(4, "Y pos: &lt; %d&gt;", nMotorEncoder[yMotor]);
		displayBigTextLine(5, "Press pos: &lt; %d&gt;", nMotorEncoder[pressMotor]);
		if(SensorValue(pressHome) == 1){
			displayBigTextLine(2, "Press is on, &lt; %d&gt;", SensorValue(pressHome));}
		else {
			displayBigTextLine(2, "Press is off, &lt; %d&gt;", SensorValue(pressHome));
		}
	}

}



/********************************************************
*   Calibration X - Axis
********************************************************/
void calibrateX(){
	while(SensorValue(xHome) == 0){
		motor[xMotor] = -50;
	}
	motor[xMotor] = 0;
	nMotorEncoder[xMotor] = 0;        // Reste the X-Axis Motor to 0º
	xPosition = 0; xDegrees = 0;
}



/********************************************************
*   Calibration Y - Axis
********************************************************/
void calibrateY(){
	while(SensorValue(yHome) == 0){
		motor[yMotor] = -50;
	}
	motor[yMotor] = 0;
	nMotorEncoder[yMotor] = 0;        // Reste the Y-Axis Motor to 0º
	yPosition = 0; yDegrees = 0;
}



/********************************************************
*  Press Bottle
********************************************************/
void pressBottle(bool enabled)   //True = pen down, write; False = pen up
{
	if (enabled == false) {
		displayBigTextLine(1, "Press on:  &lt; %d&gt;", nMotorEncoder[pressMotor]);
		while(SensorValue(pressHome) == 0){motor[pressHome] = -10;}      // Raise the Pen
		motor[pressMotor] = 0;
		nMotorEncoder[pressMotor] = 0;
		//    penPosition = false;
	}

	if (enabled == true) {
		displayBigTextLine(1, "Press off: &lt; %d&gt;", nMotorEncoder[pressMotor]);
		while(nMotorEncoder[pressMotor] < 250){motor[pressMotor] = 10;}   // Lower the Pen by 250º to Draw
		motor[pressMotor] = 0;
		penPosition = true; }
}



/********************************************************
*   Movement functions
********************************************************/
void moveLinear(int amountToMoveX, int amountToMoveY){
	xPosition = xPosition+amountToMoveX;
	yPosition = yPosition+amountToMoveY;
	if(xPosition <= 1400 && yPosition <= 1400){
		xDegrees = 5*xPosition; // xDegrees = 5x Current xPosition;
		yDegrees = 5*yPosition; // yDegrees = 5x Current yPosition;
		if(xDegrees > nMotorEncoder[yMotor]){
			motor[yMotor] = 20/abs(amountToMoveY/amountToMoveX)+1;
		}
		else{
			motor[yMotor] = -20/abs(amountToMoveY/amountToMoveX)+1;
		}
		if(yDegrees > nMotorEncoder[motorA]){
			motor[xMotor] = 20/abs(amountToMoveX/amountToMoveY)+1;
		}
		else{
			motor[xMotor] = -20/abs(amountToMoveX/amountToMoveY)+1;
		}
		while(xDegrees != 1 || yDegrees != 1){
			if(nMotorEncoder[yMotor] > xDegrees-3 && nMotorEncoder[yMotor] < xDegrees+3){
				motor[yMotor] = 0;
				xDegrees = 1;
			}
			if(nMotorEncoder[xMotor] > yDegrees-2 && nMotorEncoder[xMotor] < yDegrees+2){
				motor[xMotor] = 0;
				yDegrees = 1;
			}
		}
	}
}



/********************************************************
*   Draw Squares
********************************************************/
void drawSquares(){
	moveLinear(20,20);
	pressBottle(true);
	moveLinear(50,0);
	moveLinear(0,50);
	moveLinear(-50,0);
	moveLinear(0,-57);
	moveLinear(50,50);
	pressBottle(false);

	moveLinear(20,20);
	pressBottle(true);
	moveLinear(70,0);
	moveLinear(0,70);
	moveLinear(-70,0);
	moveLinear(0,-77);
	pressBottle(false);

	pressBottle(false);
	moveLinear(20,20);
	pressBottle(true);
	moveLinear(100,0);
	moveLinear(0,100);
	moveLinear(-100,0);
	moveLinear(0,-107);
	pressBottle(false);

	pressBottle(false);
	moveLinear(-50,150);

	wait1Msec(10000);
}


/********************************************************
*   Write the word "LEGO!"
********************************************************/
void WriteLEGO(){
	pressBottle(false);
	moveLinear(10,10);
	// Letter 'L'
	pressBottle(true);
	moveLinear(10,0);
	moveLinear(0,40);
	moveLinear(30,0);
	moveLinear(0,10);
	moveLinear(-40,0);
	moveLinear(0,-55);
	pressBottle(false);

	moveLinear(60,0);

	// Letter 'E'
	pressBottle(true);
	moveLinear(40,0);
	moveLinear(0,15);
	moveLinear(-30,0);
	moveLinear(0,10);
	moveLinear(20,0);
	moveLinear(0,10);
	moveLinear(-20,0);
	moveLinear(0,5);
	moveLinear(30,0);
	moveLinear(0,10);
	moveLinear(-40,0);
	moveLinear(0,-50);
	pressBottle(false);

	moveLinear(60,0);

	// Letter 'G'
	pressBottle(true);
	moveLinear(40,0);
	moveLinear(0,15);
	moveLinear(-30,0);
	moveLinear(0,30);
	moveLinear(20,0);
	moveLinear(0,-15);
	moveLinear(-10,0);
	moveLinear(0,-10);
	moveLinear(20,0);
	moveLinear(0,30);
	moveLinear(-40,0);
	moveLinear(0,-50);
	pressBottle(false);

	moveLinear(60,0);

	// Letter '0'
	pressBottle(true);
	moveLinear(40,0);
	moveLinear(0,50);
	moveLinear(-40,0);
	moveLinear(0,-55);
	pressBottle(false);
	moveLinear(10,15);
	pressBottle(true);
	moveLinear(20,0);
	moveLinear(0,30);
	moveLinear(-20,0);
	moveLinear(0,-35);
	pressBottle(false);

	moveLinear(60,0);

	// Letter '!'
	pressBottle(true);
	moveLinear(10,0);
	moveLinear(0,30);
	moveLinear(-10,0);
	moveLinear(-30,0);
	pressBottle(false);
	moveLinear(0,40);
	pressBottle(true);
	moveLinear(10,0);
	moveLinear(0,10);
	moveLinear(-10,0);
	moveLinear(0,10);
	pressBottle(false);

	moveLinear(-60,100);

	wait1Msec(10000);
}



/********************************************************
*   LEGO Mindstorms NXT X-Y Plotter
********************************************************/
task main()
{
	eraseDisplay();
	startTask(monitorPlotter);
	wait1Msec(2000);
	pressBottle(false);
	calibrateY();
	calibrateX();
	wait1Msec(2000);

	// Write the Word "LEGO!"
	WriteLEGO();

	// Move Back to show Drawing
	calibrateX();
	moveLinear(0,150);

	wait1Msec(20000); // Wait 20 Seconds to Change Paper

	// Begin Drawing Squares
	drawSquares();

	// Move Back to show Drawing
	calibrateX();
	moveLinear(0,150);

	wait1Msec(20000); // Wait 20 Seconds to Change Paper

	pressBottle(false);
	calibrateY();
	calibrateX();
}
